### PR TITLE
Change percona to shatteredsilicon

### PR DESCRIPTION
**Pull request by oblitorum**

### CODE REVIEW

**Comment by gordan-bobic** [comment]
This looks concerning:
"The diff you're trying to view is too large. We only load the first 3000 changed files."
 Can you directly send me the diff?

Regarding the service and spec file, does node_exporter have a separate rpm and service script in pmm-server? I just checked in a deployed PMM 1.17.5 server and there is no node_exporter rpm, there is only pmm-client rpm. I can see that there is /usr/lib/systemd/system/node_exporter.service, but this is part of the pmm-server package.

**Comment by oblitorum** [comment]
> Regarding the service and spec file, does node_exporter have a separate rpm and service script in pmm-server? I just checked in a deployed PMM 1.17.5 server and there is no node_exporter rpm, there is only pmm-client rpm. I can see that there is /usr/lib/systemd/system/node_exporter.service, but this is part of the pmm-server package.

You are right, node_exporter doesn't have a separate rpm, it's part of ssm-client package, and the service script is part of  ssm-server package. I just bindly retrieved them from ssm-server-packaging repo, didn't realize they are not being used in  this repo. I just removed them.

**Comment by gordan-bobic** [comment]
What do we need this for? It looks Windows specific?

Gopkg.lock:
[[projects]]
digest = "1:870d441fe217b8e689d7949fef6e43efbc787e50f200cb1e70dbca9204a1d6be"
name = "github.com/inconshreveable/mousetrap"
packages = ["."]
pruneopts = ""
revision = "76626ae9c91c4f2a10f34cad8ce83ea42c93bb75"
version = "v1.0"

**Comment by gordan-bobic** [comment]
What is this needed for?

[[projects]]
  digest = "1:cac7b81408ca879701c546d8f9bf402ed23dfde8099710e17aa6cfb705c3b15b"
  name = "github.com/magiconair/properties"
  packages = ["."]
  pruneopts = ""
  revision = "869a5592420f4ff6ebf74500b5c658b29d973172"
  version = "v1.8.6"

**Comment by gordan-bobic** [comment]
Similarly these don't seem to be in the original:

[[projects]]
  digest = "1:4a56bbeaad607aef800a2c006b820fc48f9ba5f8a52f5f03e6150a62f0700b54"
  name = "github.com/pelletier/go-toml"
  packages = ["."]
  pruneopts = ""
  revision = "fed1464066413075eac02cd4dc368b5221845541"
  version = "v1.9.5"

[[projects]]
  digest = "1:c45802472e0c06928cd997661f2af610accd85217023b1d5f6331bebce0671d3"
  name = "github.com/pkg/errors"
  packages = ["."]
  pruneopts = ""
  revision = "614d223910a179a466c1767a985424175c39b465"
  version = "v0.9.1"

[[projects]]
  digest = "1:d6eef4c078b948de74bddbcae27302a85085e29fadcfa8cb9af880d21cf8d127"
  name = "github.com/spf13/cast"
  packages = ["."]
  pruneopts = ""
  revision = "2b0eb0f724e320b655240e331aef36d1175986c2"
  version = "v1.5.0"

[[projects]]
  digest = "1:2edf60ac3fa73835649b8a555d0efbc1a46479e01d5ceae0b90a5330747e1754"
  name = "github.com/spf13/cobra"
  packages = ["."]
  pruneopts = ""
  revision = "5b2b9e9f61d36ccb66167301f76a2292c3729855"
  version = "v1.4.0"

[[projects]]
  digest = "1:cc15ae4fbdb02ce31f3392361a70ac041f4f02e0485de8ffac92bd8033e3d26e"
  name = "github.com/spf13/jwalterweatherman"
  packages = ["."]
  pruneopts = ""
  revision = "94f6ae3ed3bceceafa716478c5fbf8d29ca601a1"
  version = "v1.1.0"

[[projects]]
  digest = "1:688428eeb1ca80d92599eb3254bdf91b51d7e232fead3a73844c1f201a281e51"
  name = "github.com/spf13/pflag"
  packages = ["."]
  pruneopts = ""
  revision = "2e9d26c8c37aae03e3f9d4e90b7116f5accb7cab"
  version = "v1.0.5"

[[projects]]
  digest = "1:eab61c111b790f90c737d83a2f6ff6e5f1f7c073f152d295ad3556fb0ddb3e20"
  name = "github.com/spf13/viper"
  packages = ["."]
  pruneopts = ""
  revision = "a1b837276271029e31f796ae5d03ba9ffb017244"
  version = "v1.0.3"

[[projects]]
  digest = "1:b9d5d15946537023d2ecb25955519ac7f055f459d48dc5876262d4859789bfb3"
  name = "golang.org/x/text"
  packages = [
    "internal/gen",
    "internal/triegen",
    "internal/ucd",
    "transform",
    "unicode/cldr",
    "unicode/norm",
  ]
  pruneopts = ""
  revision = "383b2e75a7a4198c42f8f87833eefb772868a56f"
  version = "v0.3.7"

[[projects]]
  digest = "1:a62d94ae3ff2d8e36466bdc37444fdc5dc7e804d5a7ed3993eb0c3346e0e8627"
  name = "google.golang.org/protobuf"
  packages = [
    "encoding/prototext",
    "encoding/protowire",
    "internal/descfmt",
    "internal/descopts",
    "internal/detrand",
    "internal/encoding/defval",
    "internal/encoding/messageset",
    "internal/encoding/tag",
    "internal/encoding/text",
    "internal/errors",
    "internal/filedesc",
    "internal/filetype",
    "internal/flags",
    "internal/genid",
    "internal/impl",
    "internal/order",
    "internal/pragma",
    "internal/set",
    "internal/strs",
    "internal/version",
    "proto",
    "reflect/protodesc",
    "reflect/protoreflect",
    "reflect/protoregistry",
    "runtime/protoiface",
    "runtime/protoimpl",
    "types/descriptorpb",
    "types/known/timestamppb",
  ]
  pruneopts = ""
  revision = "32051b4f86e54c2142c7c05362c6e96ae3454a1c"
  version = "v1.28.0"


Were they auto-pulled by dependencies?

**Comment by oblitorum** [comment]
> Were they auto-pulled by dependencies?

Yep, all of these are auto-pulled by dependencies. I might did a dependency update, and it causes a lot of changes in denpendency tree.

**Pull request merged**
